#!/bin/bash
sudo pacman-mirrors --country United_States
sudo pacman-mirrors -f 0
sudo pacman -S yay pamac --noconfirm
yay -Syyua --noconfirm

yay -Sy base-devel --noconfirm
yay -S linux50-headers timeshift gnome-disk-utility stacer-bin --noconfirm

sudo mkdir -p /media/hdd
sudo chmod -R 777 /media/hdd
echo "mount hard drive to /media/hdd using gnome-disk-utility"

echo "Installing arc-kde theme:"
pkgs="arc-kde papirus-icon-theme papirus-maia-icon-theme"
echo $pkgs
yay -S $pkgs --noconfirm

echo "System Settings - Workspace Theme -- Look And Feel - Arc Dark"
echo "Backup system using timeshift"

# echo "System Settings - Hardware Configuration - Install video-nvidia"
# nvidia-smi
