#!/bin/bash

echo "Add Dropbox key:"
gpg --recv-keys 1C61A2656FB57B7E4DE0F4C1FC918B335044912E

echo "Installing the following essential packages:"

yay -S dropbox insync syncthing-bin syncthingdesktop syncthing-gtk syncthing-discosrv --noconfirm

echo "sudo sysctl fs.inotify.max_user_instances=256" > ./30-dropbox.conf
echo "sudo sysctl fs.inotify.max_user_watches=1048576" >> ./30-dropbox.conf
echo "sudo sysctl fs.inotify.max_user_instances=256" > ./50-max_user_watches.conf
echo "sudo sysctl fs.inotify.max_user_watches=1048576" >> ./50-max_user_watches.conf
sudo mv ./30-dropbox.conf /etc/sysctl.d/30-dropbox.conf
sudo mv ./50-max_user_watches.conf /etc/sysctl.d/50-max_user_watches.conf

echo "Installation finished!"
