#!/bin/bash

echo "Installing the following essential packages:"

pkgs="softmaker-office-2024-bin xorg-xkill anydesk-bin screenkey filezilla flameshot ksnip obs-studio wavebox gedit gufw hardinfo jre notepadqq plasma5-applets-eventcalendar rar etcher-bin peek pinta kdenlive gcc-fortran rustup zoom icaclient elisa obsidian"

echo $pkgs

yay -S $pkgs --noconfirm

echo "Installation finished!"
