#!/bin/bash

echo "Installing the following optional packages:"

pkgs="calibre gimp gscan2pdf inkscape xnconvert libreoffice-extension-languagetool mathpix-snipping-tool masterpdfeditor remmina pdfstudio skypeforlinux-stable-bin teamviewer ttf-ms-fonts electronic-wechat variety"

echo $pkgs

yay -S $pkgs --noconfirm

sudo teamviewer --daemon enable
sudo teamviewer --daemon start
sudo systemctl enable teamviewerd

echo "Installation finished!"
