#!/bin/bash

echo "Installing the following optional packages:"

pkgs="calibre gimp gscan2pdf inkscape libreoffice-extension-languagetool masterpdfeditor remmina pdfstudio skypeforlinux-stable-bin teamviewer ttf-ms-fonts electronic-wechat"

echo $pkgs

yay -S $pkgs --noconfirm

sudo teamviewer --daemon enable
sudo teamviewer --daemon start
sudo systemctl enable teamviewerd

echo "Installation finished!"
