#!/bin/bash

echo "Installing the following programming packages:"
pkgs="r rstudio-desktop-bin ruby ruby-rdoc visual-studio-code-bin bazel google-cloud-sdk"
echo $pkgs
yay -S $pkgs --noconfirm

mkdir -p ~/miniconda3
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda3/miniconda.sh
bash ~/miniconda3/miniconda.sh -b -u -p ~/miniconda3
rm ~/miniconda3/miniconda.sh

~/miniconda3/bin/conda init bash
~/miniconda3/bin/conda init zsh

echo "Installation finished!"

source ~/.zshrc

git config --global user.name "Qiusheng Wu"
git config --global user.email "giswqs@gmail.com"
git config --global credential.helper store
conda config --set auto_activate_base false

# echo "[ -f /opt/miniconda3/etc/profile.d/conda.sh ] && source /opt/miniconda3/etc/profile.d/conda.sh" >> ~/.zshrc
# sudo ln -s /opt/miniconda3/etc/profile.d/conda.sh /etc/profile.d/conda.sh
# source ~/.zshrc

