#!/bin/bash

echo "Installing video driver"
yay -S linux50-nvidia nvidia-utils --noconfirm  
nvidia-smi

yay -S cuda cudnn --noconfirm  
echo "export PATH=/opt/cuda/bin${PATH:+:${PATH}}" >> ~/.bashrc
echo "export LD_LIBRARY_PATH=/opt/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"  >> ~/.bashrc
source ~/.bashrc

yay -S python-tensorflow-cuda

echo "Installing the following programming packages:"
pkgs="r rstudio-desktop-bin rstudio-server-bin ruby ruby-rdoc visual-studio-code-bin bazel"
echo $pkgs
yay -S $pkgs --noconfirm

sudo rstudio-server start
sudo systemctl enable rstudio-server
gem update --user-install
gem install jekyll --user-install
echo "add $HOME/.gem/ruby/2.5.0/bin to system PATH"
echo "export PATH=$PATH:$HOME/.gem/ruby/2.5.0/bin" >> ~/.bashrc
source ~/.bashrc

echo "Installing Anaconda ..."
yay -S anaconda --noconfirm
echo "export PATH=$PATH:/opt/anaconda/bin" >> ~/.bashrc
source ~/.bashrc
anaconda --version && conda --version

echo "Installing PyCharm ..."
yay -S pycharm-professional --noconfirm
sudo chmod 777 -R /opt/pycharm-professional/

echo "Creating conda environment ..."
conda create -n py36 python=3.6 -y
source activate py36
conda install numpy matplotlib pandas scipy scikit-learn scikit-image h5py notebook ipykernel -y --name py36
ipython kernel install --user --name="py36"

conda create -n py27 python=2.7 -y
source activate py27
conda install numpy matplotlib pandas scipy scikit-learn scikit-image h5py notebook ipykernel -y --name py27
ipython kernel install --user --name="py27"

echo "Installation finished!"
