#!/bin/bash

git config --global user.name "Qiusheng Wu"
git config --global user.email "giswqs@gmail.com"
git config --global credential.helper store
conda config --set auto_activate_base false

conda install -n base mamba -c conda-forge -y
conda create -n qgis python=3.12 -y
conda activate qgis && mamba install -c conda-forge libgdal-arrow-parquet pyarrow gdal qgis pygis jupyterlab -y
conda activate qgis && mamba update -c conda-forge sqlite -y
cp ~/miniconda3/envs/qgis/lib/libsqlite3.so.3.49.1 ~/miniconda3/envs/qgis/lib/libsqlite3.so
