#!/bin/bash

git config --global user.name "Qiusheng Wu"
git config --global user.email "giswqs@gmail.com"
git config --global credential.helper store
conda config --set auto_activate_base false

conda install -n base mamba -c conda-forge -y
conda create -n qgis python=3.12 -y
source ~/miniconda3/etc/profile.d/conda.sh
conda activate qgis && mamba install -c conda-forge libgdal-arrow-parquet pyarrow gdal qgis pygis jupyterlab -y
conda activate qgis && mamba update -c conda-forge sqlite -y
cp ~/miniconda3/envs/qgis/lib/libsqlite3.so.3.49.1 ~/miniconda3/envs/qgis/lib/libsqlite3.so


conda create -n geo python=3.12 -y
source ~/miniconda3/etc/profile.d/conda.sh
conda activate geo && mamba install -c conda-forge libgdal-arrow-parquet pyarrow gdal geoai jupyterlab jupyterhub jupyter-server-proxy jupytext mystmd geemap -y
conda activate geo && mamba update -c conda-forge sqlite -y
cp ~/miniconda3/envs/geo/lib/libsqlite3.so.3.49.1 ~/miniconda3/envs/geo/lib/libsqlite3.so


# conda activate geo
# cd /path/to/start_dir/
# jupyterhub --generate-config

# c.Authenticator.allow_all = True
# c.Spawner.notebook_dir = '/path/to/start_dir/'

# jupyterhub -f /path/to/jupyterhub_config.py