#!/bin/bash

echo "alias up='yay -Syyua'"  >> ~/.bashrc
echo "alias ug='yay -Sua --noconfirm'" >> ~/.bashrc
echo "alias py37='conda activate py37'" >> ~/.bashrc
echo "alias py27='conda activate py27'" >> ~/.bashrc
echo "alias pygeo='conda activate pygeo'" >> ~/.bashrc
echo "alias pytest='conda activate pytest'" >> ~/.bashrc
echo "alias arcgis='conda activate arcgis'" >> ~/.bashrc
echo "alias nb='jupyter notebook'" >> ~/.bashrc
echo "alias pdf2doc='soffice --infilter=\"writer_pdf_import\" --convert-to doc'" >> ~/.bashrc
echo "alias touchall='find  -type f  -exec touch {} +'" >> ~/.bashrc
echo "alias jk='jekyll serve --watch --port 8000'" >> ~/.bashrc
echo "alias hi='function hdi(){ howdoi \$* -c -n 5; }; hdi'" >> ~/.bashrc
echo "alias eb='gedit ~/.bashrc'" >> ~/.bashrc
echo "alias sb='source ~/.bashrc'" >> ~/.bashrc
echo "alias la='du -ah . | grep -v \"/$\" | sort -h'" >> ~/.bashrc
echo "alias ld='du -a -h --max-depth=1 | sort -h'" >> ~/.bashrc
echo "alias lf='ls -1Rhs | sed -e \"s/^ *//\" | grep \"^[0-9]\" | sort -h'" >> ~/.bashrc
# alias listfiles='ls -1Rhs | sed -e "s/^ *//" | grep "^[0-9]" | sort -h'
# echo "alias unzipall='for i in *.zip; do unzip \"$i\" -d \"${i%%.zip}\"; done'" >> ~/.bashrc
# alias unzipall='for i in *.zip; do unzip "$i" -d "${i%%.zip}"; done'
# echo "alias touchall='find  -exec touch {} +'" >> ~/.bashrc
#echo "Ignore packages upgrade ..."
#sudo echo "IgnorePkg = cudnn cuda linux414-nvidia linux415-nvidia" >> /etc/pacman.conf
source ~/.bashrc