#!/bin/bash

echo "Installing video driver"
yay -S linux61-nvidia-470xx nvidia-utils --noconfirm  
nvidia-smi

echo "Installing cuda and cudnn ..."
# pkgs="linux61-nvidia nvidia-utils cuda cudnn"
pkgs="cuda cudnn"
echo $pkgs
yay -S $pkgs --noconfirm

echo "export PATH=/opt/cuda/bin${PATH:+:${PATH}}" >> ~/.bashrc
echo "export LD_LIBRARY_PATH=/opt/cuda/lib64${LD_LIBRARY_PATH:+:${LD_LIBRARY_PATH}}"  >> ~/.bashrc
source ~/.bashrc

echo "Checking cuda and cudnn versions:"
sudo ldconfig
# sudo mhwd -a pci nonfree 0300
nvidia-smi
nvcc --version
cat /opt/cuda/include/cudnn.h | grep CUDNN_MAJOR -A 2

# echo "Ignore packages upgrade ..."
# sudo echo "IgnorePkg = cudnn cuda linux61-nvidia" >> /etc/pacman.conf

echo "Installation finished!"
