#!/bin/bash

echo "Installing tensorflow-gpu for cuda and cudnn ..."
yay -S python-tensorflow-cuda

echo "Installation finished!"

echo "Creating conda environment ..."
conda create -n dl python -y
conda activate dl
conda install tensorflow-gpu keras pytorch torchvision cudatoolkit notebook ipykernel -y --name dl
ipython kernel install --user --name="dl"

conda install -c conda-forge earthengine-api -y
