#!/bin/bash

echo "Installing tensorflow-gpu for cuda and cudnn ..."
yay -S python-tensorflow-cuda

# test tensorflow
# import tensorflow as tf
# hello = tf.constant('Hello, TensorFlow!')
# sess = tf.Session()
# print(sess.run(hello))

echo "Installation finished!"
